service: aws-node-next-ssr

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs8.10
  memorySize: 256
  timeout: 15
  environment:
    NODE_ENV: production

functions:
  next:
    handler: index.next
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  serverless-offline:
    port: 8000
    dontPrintOutput: true
